spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/kbt-auth?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true